### ISSUE TITLE
Startup Crash | NoClassDefFoundError

### ISSUE THREAD

**Issue by ghost** [Ling-ALY/Jumpy-Boat-Fabric#2]
Part of the stack trace pertaining to this mod:

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'jumpyboat'!
	at net.minecraft.class_310.mdf9c8d4$lambda$invoke$4$3(class_310.java:7535)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.minecraft.class_310.mdf9c8d4$lambda$invoke$5$2(class_310.java:7533)
	at net.minecraft.class_310.redirect$znk000$init(class_310.java:7499)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: org/json/simple/parser/ParseException
```

Let me know if you need more info!

**Comment by Alan-Yan-CanMeng** [comment]
sorry,I was at the hospital in the past month so I didn't manage this mod these days.
now v1.0 for 1.19 is published.If you wangt the version for 1.18 or other minecraft versions reply at curseforge

**Comment by ghost** [comment]
> sorry,I was at the hospital in the past month so I didn't manage this mod these days.

Oh my! Your health is way more important than any mod, so don't worry about it at all!

I hope you're doing better now - and thank you for getting back to me. 😄
